/*
 * Generated by JasperReports - 20/9/24 9:35 AM
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;



/**
 *
 */
public class report32name_1726805128824_490147 extends JREvaluator
{


    /**
     *
     */
    private JRFillVariable variable_PAGE_NUMBER = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        )
    {
        initParams(pm);
        initFields(fm);
        initVars(vm);
    }


    /**
     *
     */
    private void initParams(Map pm)
    {
    }


    /**
     *
     */
    private void initFields(Map fm)
    {
    }


    /**
     *
     */
    private void initVars(Map vm)
    {
        variable_PAGE_NUMBER = (JRFillVariable)vm.get("PAGE_NUMBER");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 12 : 
            {
                value = new java.util.Date(); //$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = "C:\\Users\\mahek\\Downloads\\logo2-removebg-preview.jpg"; //$JR_EXPR_ID=13$
                break;
            }
            case 20 : 
            {
                value = "Page "+((java.lang.Integer)variable_PAGE_NUMBER.getValue())+" of"; //$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = " " + ((java.lang.Integer)variable_PAGE_NUMBER.getValue()); //$JR_EXPR_ID=21$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 12 : 
            {
                value = new java.util.Date(); //$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = "C:\\Users\\mahek\\Downloads\\logo2-removebg-preview.jpg"; //$JR_EXPR_ID=13$
                break;
            }
            case 20 : 
            {
                value = "Page "+((java.lang.Integer)variable_PAGE_NUMBER.getOldValue())+" of"; //$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = " " + ((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()); //$JR_EXPR_ID=21$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 12 : 
            {
                value = new java.util.Date(); //$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = "C:\\Users\\mahek\\Downloads\\logo2-removebg-preview.jpg"; //$JR_EXPR_ID=13$
                break;
            }
            case 20 : 
            {
                value = "Page "+((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue())+" of"; //$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = " " + ((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()); //$JR_EXPR_ID=21$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
